import Head from "next/head";
import SideBar from "./SideBar";
import Header from "./Header";
import styles from "../styles/Home.module.css";

const Container = (props) => (
  <div>
     <Head >
        <title>Intervenciones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/management-icon.png" />
        
      </Head>
    <SideBar />
    <Header />
    <div className={styles.contenetcontainerLayout}>
      <div>{props.children}</div>
    </div>
  </div>
);

export default Container;
